stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    docker build -t game_of_rapprochement_bot .

test-job:
  stage: test
  script:
    echo "test"
    # docker run -it --rm game_of_rapprochement_bot -s -v

deploy-job:
  stage: deploy
  script:
    docker-compose up -d