version: '3.8'

services:
  game_of_rapprochement_bot:
    build:
      context: .
    env_file:
      - .env
    environment:
      - Token_tg=${Token_tg}
      - Your_user_ID=${Your_user_ID}
      - db=${db}
      
    volumes:
      - ./logs:/app/logs
    restart: always
