version: '3.8'

services:
  game_of_rapprochement_bot:
    build:
      context: .
    env_file:
      - .env
    environment:
      - API_KEY=${API_KEY}  # Используем переменную API_KEY
    volumes:
      - ./logs:/app/logs
    restart: always
